# Generated by Django 4.2.10 on 2024-04-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_orders_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': (('can_mark_shipped', 'Can mark order as shipped'),)},
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set(),
        ),
    ]
