# Generated by Django 5.0.4 on 2024-04-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_orders_options_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='revision_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter revision number', null=True),
        ),
    ]
