# Generated by Django 5.0.4 on 2024-04-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_orders_revision_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_amount',
            field=models.FloatField(blank=True, help_text='Enter discount amount', null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='extended_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter extended amount', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter freight', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_standard_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter product standard cost', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sales_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter sales amount', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tax_amt',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter tax amount', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_product_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Enter total product cost', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='unit_price_discount_pct',
            field=models.FloatField(blank=True, help_text='Enter unit price discount percent', null=True),
        ),
    ]
