# Generated by Django 5.0.4 on 2024-04-18 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_orders_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='due_date',
            field=models.ForeignKey(blank=True, help_text='Select due date', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_due_date', to='catalog.date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ship_date',
            field=models.ForeignKey(blank=True, help_text='Select ship date', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_ship_date', to='catalog.date'),
        ),
    ]
