# Generated by Django 5.0.4 on 2024-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='sales_order_number',
            field=models.CharField(blank=True, help_text='Enter sales order number', max_length=20),
        ),
    ]
