# Generated by Django 5.0.4 on 2024-04-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_count',
            field=models.IntegerField(default=100, help_text='Inventory count of the product'),
        ),
    ]
