# Generated by Django 5.0.4 on 2024-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_inventory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='calendar_semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='fiscal_quarter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='fiscal_semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='fiscal_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
